### ISSUE TITLE
템플릿 상속

### ISSUE THREAD

**Issue by lee-sj** [kim-taeho1351/django_0811#1]
https://github.com/kim-taeho1351/django_0811/blob/395dab96f9effcf10bed2898382a87ec6743531c/blog/templates/index.html#L1

해당 코드가 정상 작동 하나요? (base.html 상속)

**Comment by kim-taeho1351** [comment]
로컬에서는 정상 작동해요. 
혹시 "여기는 index.html 내부 입니다. "  메세지가 출력되지 않으시나요? @lee-sj

**Comment by lee-sj** [comment]
그건 아닌데 settings 에서는 project 폴더내부의 templates 을 설정하였는데 blog에 base 를 넣으셨길래 궁금해서요
https://github.com/kim-taeho1351/django_0811/blob/395dab96f9effcf10bed2898382a87ec6743531c/myproject/settings.py#L58

그냥 blog에 해도 작동할것 같아서 해보시고 작동을 확인하고 마무리 하신거면 문제 없습니다. 
( 이런것은 강의의 활용 / 코드의 자기화여서 적극 권장합니다. )

**Comment by kim-taeho1351** [comment]
아.. blog에서 사용되는 base라고 생각하여 실수로 blog에 넣은 것 같아요.
 위 코드가 정상 작동하는 것은 아마 blog를 담고있는 폴더와 프로젝트 폴더의 이름이 같아서 운 좋게도 정상적으로 작동된 것 같아요;;

'DIRS': ['blog/templates'], 로  고치는게 더 바람직한 것 같아  수정하여 푸쉬 하도록 하겠습니다. @lee-sj

**Comment by lee-sj** [comment]
저도 정확히 이게 원래 맞는 방법중 한가지 인지 틀린방법인데 우연히 정상작동한것인지는 잘 모르겠어요 ㅎㅎ
고치는것은 자유롭게 하셔도 될것 같습니다만 settings 를 바꾸든 파일위치를 바꾸든  두가지중 한개는 하는게 좋을거 같아요
지금있는건 엇갈리는 코드인거 같아서 나중에 문제가 생기거나 오류생기면 찾기 힘들수도 있을것 같아서요

**Comment by kim-taeho1351** [comment]
넵!! 감사합니다. @lee-sj
